name: release
run-name: Publish new version of library
on:
  push:
    branches:
      - 'main'
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g pnpm
      - run: pnpm install
      - run: npx semantic-release


  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: echo $GITHUB_WORKFLOW
      - run: echo $GH_TOKEN
      - run: echo $GH_TOKEN
      - run: echo $NPM_TOKEN
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm run test
      - run: pnpm run lint
